package:
  name: pylimer-tools
  version: 0.3.14
  top-level:
    - pylimer_tools

source:
  url: https://github.com/GenieTim/pylimer-tools/releases/download/v0.3.14/pylimer_tools-0.3.14-cp313-cp313-pyodide_2025_0_wasm32.whl
  sha256: f5885148702e7ac4c36518dc5c5104099425ecb17683ac23b3ad031a57bffc26

test:
  imports:
    - pylimer_tools
    - pylimer_tools_cpp

requirements:
  run:
    - numpy

about:
  home: https://github.com/GenieTim/pylimer-tools
  PyPI: https://pypi.org/project/pylimer-tools
  summary: A toolkit for handling bead-spring polymers and LAMMPS output in
    Python
  license: GPL-3.0-or-later
extra:
  recipe-maintainers:
    - GenieTim
